[package]
name = "des-asm-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.wasm-bindgen]
version = "0.2.83"

[dependencies.des-asm]
path = ".."

[dependencies.log]
version = "0.4.17"

[dependencies.wee_alloc]
version = "0.4.5"
